version: '3.4'

services:
  nterpol:
    image: nterpol
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      STAGE: denemes
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:1111@postgres:5432/denemes
    networks:
      - default  
    ports:
      - 5000:5000
  postgres:
    image: 'postgres'
    networks:
      - default
    container_name: 'postgresdb'
    ports:
      - '54320:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1111}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    networks:
      - default
    container_name: 'musing'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-elmas@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminn}
volumes:
  postgres-data:
